source 'https://rubygems.org' #get my gems from rubygems

gem 'sinatra' #include sinatra
gem 'json' #include json
gem 'sinatra-cross_origin' #include sinatra cross origin to let other servers access the api.
