# Site settings
title: Ireneusz Eric Luczak
email: luczak.irek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: luczak_eric
github_username:  luczaki114

# Build settings
markdown: kramdown
